name: Simple Echo CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkQuality:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: |
          lint image:node:16
          sleep 5