name: Simple Echo CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkQuality:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
        run: |
          npm run lint
          sleep 5