name: Simple Echo CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis
      environment:
        type: environment

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo and Sleep
        run: |
          echo "Hello job from Test"
          sleep 5

  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo and Sleep
        run: |
          echo "hello job from First Stage"
          sleep 5

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Echo and Sleep
        run: |
          echo "hello job from Second Stage"
          sleep 5

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Echo and Sleep Longer
        run: |
          echo "hello job from Second Stage (Longer Sleep)"
          sleep 30

  job4:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.include_job4 == 'true' }}
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Echo and Sleep
        run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
